In [10]:
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [11]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [12]:
!pip install some_library

Requirement already satisfied: some_library in /usr/local/lib/python3.12/dist-packages (0.0.1)
Requirement already satisfied: spatialdata>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from some_library) (0.7.2)
Requirement already satisfied: anndata>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (0.12.10)
Requirement already satisfied: annsel>=0.1.2 in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (0.1.2)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (8.3.1)
Requirement already satisfied: dask-image in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (2025.11.0)
Requirement already satisfied: dask<2026.1.2,>=2025.2.0 in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (2026.1.1)
Requirement already satisfied: datashader in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (0.19.0)
Requirement already satisfied: distributed<2026.1.2 in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (2026.1.1)
Requirement already satisfied: fsspec[http,s3] in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (2025.3.0)
Requirement already satisfied: geopandas>=0.14 in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (1.1.3)
Requirement already satisfied: multiscale-spatial-image==2.0.3 in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (2.0.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (3.6.1)
Requirement already satisfied: numba>=0.55.0 in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (0.60.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (2.0.2)
Requirement already satisfied: ome-zarr>=0.12.2 in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (0.14.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (2.2.2)
Requirement already satisfied: pooch in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (1.9.0)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (18.1.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (13.9.4)
Requirement already satisfied: scikit-image in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (0.25.2)
Requirement already satisfied: scipy!=1.17.0 in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (1.16.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (75.2.0)
Requirement already satisfied: shapely>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (2.1.2)
Requirement already satisfied: spatial-image>=1.2.3 in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (1.2.3)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (4.15.0)
Requirement already satisfied: universal-pathlib>=0.2.6 in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (0.3.10)
Requirement already satisfied: xarray-spatial>=0.3.5 in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (0.9.6)
Requirement already satisfied: xarray>=2024.10.0 in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (2025.12.0)
Requirement already satisfied: zarr>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from spatialdata>=0.2.0->some_library) (3.1.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from multiscale-spatial-image==2.0.3->spatialdata>=0.2.0->some_library) (2.9.0.post0)
Requirement already satisfied: xarray-dataclass>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from multiscale-spatial-image==2.0.3->spatialdata>=0.2.0->some_library) (3.0.0)
Requirement already satisfied: array-api-compat>=1.7.1 in /usr/local/lib/python3.12/dist-packages (from anndata>=0.9.1->spatialdata>=0.2.0->some_library) (1.14.0)
Requirement already satisfied: h5py>=3.8 in /usr/local/lib/python3.12/dist-packages (from anndata>=0.9.1->spatialdata>=0.2.0->some_library) (3.16.0)
Requirement already satisfied: legacy-api-wrap in /usr/local/lib/python3.12/dist-packages (from anndata>=0.9.1->spatialdata>=0.2.0->some_library) (1.5)
Requirement already satisfied: natsort in /usr/local/lib/python3.12/dist-packages (from anndata>=0.9.1->spatialdata>=0.2.0->some_library) (8.4.0)
Requirement already satisfied: packaging>=24.2 in /usr/local/lib/python3.12/dist-packages (from anndata>=0.9.1->spatialdata>=0.2.0->some_library) (26.0)
Requirement already satisfied: more-itertools>=10.7 in /usr/local/lib/python3.12/dist-packages (from annsel>=0.1.2->spatialdata>=0.2.0->some_library) (10.8.0)
Requirement already satisfied: narwhals>=2.14 in /usr/local/lib/python3.12/dist-packages (from narwhals[pandas]>=2.14->annsel>=0.1.2->spatialdata>=0.2.0->some_library) (2.18.1)
Requirement already satisfied: session-info2 in /usr/local/lib/python3.12/dist-packages (from annsel>=0.1.2->spatialdata>=0.2.0->some_library) (0.4)
Requirement already satisfied: tqdm>=4 in /usr/local/lib/python3.12/dist-packages (from annsel>=0.1.2->spatialdata>=0.2.0->some_library) (4.67.3)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dask<2026.1.2,>=2025.2.0->spatialdata>=0.2.0->some_library) (3.1.2)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from dask<2026.1.2,>=2025.2.0->spatialdata>=0.2.0->some_library) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from dask<2026.1.2,>=2025.2.0->spatialdata>=0.2.0->some_library) (6.0.3)
Requirement already satisfied: toolz>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from dask<2026.1.2,>=2025.2.0->spatialdata>=0.2.0->some_library) (0.12.1)
Requirement already satisfied: jinja2>=2.10.3 in /usr/local/lib/python3.12/dist-packages (from distributed<2026.1.2->spatialdata>=0.2.0->some_library) (3.1.6)
Requirement already satisfied: locket>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from distributed<2026.1.2->spatialdata>=0.2.0->some_library) (1.0.0)
Requirement already satisfied: msgpack>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from distributed<2026.1.2->spatialdata>=0.2.0->some_library) (1.1.2)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from distributed<2026.1.2->spatialdata>=0.2.0->some_library) (5.9.5)
Requirement already satisfied: sortedcontainers>=2.0.5 in /usr/local/lib/python3.12/dist-packages (from distributed<2026.1.2->spatialdata>=0.2.0->some_library) (2.4.0)
Requirement already satisfied: tblib!=3.2.0,!=3.2.1,>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from distributed<2026.1.2->spatialdata>=0.2.0->some_library) (3.2.2)
Requirement already satisfied: tornado>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from distributed<2026.1.2->spatialdata>=0.2.0->some_library) (6.5.1)
Requirement already satisfied: urllib3>=1.26.5 in /usr/local/lib/python3.12/dist-packages (from distributed<2026.1.2->spatialdata>=0.2.0->some_library) (2.5.0)
Requirement already satisfied: zict>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from distributed<2026.1.2->spatialdata>=0.2.0->some_library) (3.0.0)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from geopandas>=0.14->spatialdata>=0.2.0->some_library) (0.12.1)
Requirement already satisfied: pyproj>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from geopandas>=0.14->spatialdata>=0.2.0->some_library) (3.7.2)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.55.0->spatialdata>=0.2.0->some_library) (0.43.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from ome-zarr>=0.12.2->spatialdata>=0.2.0->some_library) (3.13.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from ome-zarr>=0.12.2->spatialdata>=0.2.0->some_library) (2.32.4)
Requirement already satisfied: rangehttpserver in /usr/local/lib/python3.12/dist-packages (from ome-zarr>=0.12.2->spatialdata>=0.2.0->some_library) (1.4.0)
Requirement already satisfied: Deprecated in /usr/local/lib/python3.12/dist-packages (from ome-zarr>=0.12.2->spatialdata>=0.2.0->some_library) (1.3.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->spatialdata>=0.2.0->some_library) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->spatialdata>=0.2.0->some_library) (2025.3)
Requirement already satisfied: platformdirs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from pooch->spatialdata>=0.2.0->some_library) (4.9.4)
Requirement already satisfied: pillow>=10.1 in /usr/local/lib/python3.12/dist-packages (from scikit-image->spatialdata>=0.2.0->some_library) (11.3.0)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in /usr/local/lib/python3.12/dist-packages (from scikit-image->spatialdata>=0.2.0->some_library) (2.37.3)
Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.12/dist-packages (from scikit-image->spatialdata>=0.2.0->some_library) (2026.3.3)
Requirement already satisfied: lazy-loader>=0.4 in /usr/local/lib/python3.12/dist-packages (from scikit-image->spatialdata>=0.2.0->some_library) (0.5)
Requirement already satisfied: pathlib-abc<0.6.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from universal-pathlib>=0.2.6->spatialdata>=0.2.0->some_library) (0.5.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from xarray-spatial>=0.3.5->spatialdata>=0.2.0->some_library) (3.10.0)
Requirement already satisfied: zstandard in /usr/local/lib/python3.12/dist-packages (from xarray-spatial>=0.3.5->spatialdata>=0.2.0->some_library) (0.25.0)
Requirement already satisfied: donfig>=0.8 in /usr/local/lib/python3.12/dist-packages (from zarr>=3.0.0->spatialdata>=0.2.0->some_library) (0.8.1.post1)
Requirement already satisfied: google-crc32c>=1.5 in /usr/local/lib/python3.12/dist-packages (from zarr>=3.0.0->spatialdata>=0.2.0->some_library) (1.8.0)
Requirement already satisfied: numcodecs>=0.14 in /usr/local/lib/python3.12/dist-packages (from zarr>=3.0.0->spatialdata>=0.2.0->some_library) (0.16.5)
Requirement already satisfied: pims>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from dask-image->spatialdata>=0.2.0->some_library) (0.7)
Requirement already satisfied: colorcet in /usr/local/lib/python3.12/dist-packages (from datashader->spatialdata>=0.2.0->some_library) (3.1.0)
Requirement already satisfied: multipledispatch in /usr/local/lib/python3.12/dist-packages (from datashader->spatialdata>=0.2.0->some_library) (1.0.0)
Requirement already satisfied: param in /usr/local/lib/python3.12/dist-packages (from datashader->spatialdata>=0.2.0->some_library) (2.3.3)
Requirement already satisfied: pyct in /usr/local/lib/python3.12/dist-packages (from datashader->spatialdata>=0.2.0->some_library) (0.6.0)
Requirement already satisfied: s3fs in /usr/local/lib/python3.12/dist-packages (from fsspec[http,s3]->spatialdata>=0.2.0->some_library) (2025.3.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->spatialdata>=0.2.0->some_library) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->spatialdata>=0.2.0->some_library) (2.20.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->ome-zarr>=0.12.2->spatialdata>=0.2.0->some_library) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->ome-zarr>=0.12.2->spatialdata>=0.2.0->some_library) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->ome-zarr>=0.12.2->spatialdata>=0.2.0->some_library) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->ome-zarr>=0.12.2->spatialdata>=0.2.0->some_library) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->ome-zarr>=0.12.2->spatialdata>=0.2.0->some_library) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->ome-zarr>=0.12.2->spatialdata>=0.2.0->some_library) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->ome-zarr>=0.12.2->spatialdata>=0.2.0->some_library) (1.23.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.10.3->distributed<2026.1.2->spatialdata>=0.2.0->some_library) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->spatialdata>=0.2.0->some_library) (0.1.2)
Requirement already satisfied: slicerator>=0.9.8 in /usr/local/lib/python3.12/dist-packages (from pims>=0.4.1->dask-image->spatialdata>=0.2.0->some_library) (1.1.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from pyogrio>=0.7.2->geopandas>=0.14->spatialdata>=0.2.0->some_library) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->multiscale-spatial-image==2.0.3->spatialdata>=0.2.0->some_library) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->ome-zarr>=0.12.2->spatialdata>=0.2.0->some_library) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->ome-zarr>=0.12.2->spatialdata>=0.2.0->some_library) (3.11)
Requirement already satisfied: wrapt<3,>=1.10 in /usr/local/lib/python3.12/dist-packages (from Deprecated->ome-zarr>=0.12.2->spatialdata>=0.2.0->some_library) (1.17.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->xarray-spatial>=0.3.5->spatialdata>=0.2.0->some_library) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->xarray-spatial>=0.3.5->spatialdata>=0.2.0->some_library) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->xarray-spatial>=0.3.5->spatialdata>=0.2.0->some_library) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->xarray-spatial>=0.3.5->spatialdata>=0.2.0->some_library) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->xarray-spatial>=0.3.5->spatialdata>=0.2.0->some_library) (3.3.2)
Requirement already satisfied: aiobotocore<3.0.0,>=2.5.4 in /usr/local/lib/python3.12/dist-packages (from s3fs->fsspec[http,s3]->spatialdata>=0.2.0->some_library) (2.26.0)
Requirement already satisfied: aioitertools<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs->fsspec[http,s3]->spatialdata>=0.2.0->some_library) (0.13.0)
Requirement already satisfied: botocore<1.41.6,>=1.41.0 in /usr/local/lib/python3.12/dist-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs->fsspec[http,s3]->spatialdata>=0.2.0->some_library) (1.41.5)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs->fsspec[http,s3]->spatialdata>=0.2.0->some_library) (1.1.0)

In [19]:
# Read csv data
df = pd.read_csv('/content/training.1600000.processed.noemoticon.csv', names=column_names, encoding='latin1', on_bad_lines='skip')

In [20]:
# print stopwords in English
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [21]:
df.shape

(1600000, 6)

In [22]:
df.head()

,target,id,date,flag,user,e_mail
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."

In [23]:
column_names = ['target', 'id', 'date', 'flag', 'user', 'e_mail']
df = pd.read_csv('/content/training.1600000.processed.noemoticon.csv',names=column_names, encoding='latin1')

In [24]:
df.shape

(1600000, 6)

In [25]:
df.head()

,target,id,date,flag,user,e_mail
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."

In [26]:
# handling the missing values
df.isnull().sum()

target    0
id        0
date      0
flag      0
user      0
e_mail    0
dtype: int64

In [27]:
df['target'].value_counts()

target
0    800000
4    800000
Name: count, dtype: int64

In [28]:
df.replace({'target': {4:1}}, inplace=True)

In [29]:
df['target'].value_counts()

target
0    800000
1    800000
Name: count, dtype: int64

0 >> Negative Tweets
1 >> Positive Tweets

In [30]:
# reduce words with stemming

p_stm = PorterStemmer()

In [31]:
def stemming(content):
  stemmed_content = re.sub('[^a-zA-Z]',' ',content)
  stemmed_content = stemmed_content.lower()
  stemmed_content = stemmed_content.split()
  stemmed_content = [p_stm.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
  stemmed_content = ' '.join(stemmed_content)
  return stemmed_content

In [32]:
df['stemmed_content'] = df['e_mail'].apply(stemming)

In [33]:
df.head()

,target,id,date,flag,user,e_mail,stemmed_content
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t...",switchfoot http twitpic com zl awww bummer sho...
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...,upset updat facebook text might cri result sch...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...,kenichan dive mani time ball manag save rest g...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,whole bodi feel itchi like fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....",nationwideclass behav mad see

In [34]:
print(df['stemmed_content'])

0          switchfoot http twitpic com zl awww bummer sho...
1          upset updat facebook text might cri result sch...
2          kenichan dive mani time ball manag save rest g...
3                            whole bodi feel itchi like fire
4                              nationwideclass behav mad see
                                 ...
1599995                           woke school best feel ever
1599996    thewdb com cool hear old walt interview http b...
1599997                         readi mojo makeov ask detail
1599998    happi th birthday boo alll time tupac amaru sh...
1599999    happi charitytuesday thenspcc sparkschar speak...
Name: stemmed_content, Length: 1600000, dtype: object

In [35]:
print(df['target'])

0          0
1          0
2          0
3          0
4          0
          ..
1599995    1
1599996    1
1599997    1
1599998    1
1599999    1
Name: target, Length: 1600000, dtype: int64

In [36]:
# data and label
x = df['stemmed_content'].values
y = df['target'].values

In [37]:
print(x)

['switchfoot http twitpic com zl awww bummer shoulda got david carr third day'
 'upset updat facebook text might cri result school today also blah'
 'kenichan dive mani time ball manag save rest go bound' ...
 'readi mojo makeov ask detail'
 'happi th birthday boo alll time tupac amaru shakur'
 'happi charitytuesday thenspcc sparkschar speakinguph h']

In [38]:
print(y)

[0 0 0 ... 1 1 1]

In [39]:
# train and test
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, stratify=y, random_state=2)

In [40]:
print(x.shape, x_train.shape, x_test.shape)

(1600000,) (1280000,) (320000,)

In [41]:
print(x_train)

['watch saw iv drink lil wine' 'hatermagazin'
 'even though favourit drink think vodka coke wipe mind time think im gonna find new drink'
 ... 'eager monday afternoon'
 'hope everyon mother great day wait hear guy store tomorrow'
 'love wake folger bad voic deeper']

In [42]:
print(x_test)

['mmangen fine much time chat twitter hubbi back summer amp tend domin free time'
 'ah may show w ruth kim amp geoffrey sanhueza'
 'ishatara mayb bay area thang dammit' ...
 'destini nevertheless hooray member wonder safe trip' 'feel well'
 'supersandro thank']

In [43]:
# convert textual data to numerical
vectorizer = TfidfVectorizer()
vectorizer.fit(x_train)

x_train = vectorizer.transform(x_train)
x_test = vectorizer.transform(x_test)

In [44]:
print(x_train)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 9453092 stored elements and shape (1280000, 461488)>
  Coords	Values
  (0, 109306)	0.3753708587402299
  (0, 185193)	0.5277679060576009
  (0, 235045)	0.41996827700291095
  (0, 354543)	0.3588091611460021
  (0, 436713)	0.27259876264838384
  (0, 443066)	0.4484755317023172
  (1, 160636)	1.0
  (2, 77929)	0.3128408075034635
  (2, 109306)	0.45911764137283173
  (2, 124484)	0.18921559608014152
  (2, 129411)	0.2907419272795715
  (2, 132311)	0.20289715703997943
  (2, 150715)	0.1880385058320795
  (2, 178061)	0.1619010109445149
  (2, 266729)	0.24123230668976978
  (2, 288470)	0.16786949597862735
  (2, 406399)	0.32105459490875526
  (2, 407301)	0.18709338684973034
  (2, 409143)	0.15169282335109838
  (2, 433560)	0.32965958980285653
  (2, 443430)	0.33485996702528453
  (3, 56476)	0.5200465453608686
  (3, 151770)	0.278559647704793
  (3, 158711)	0.4456939372299574
  (3, 172421)	0.37464146922154384
  :	:
  (1279996, 291078)	0.17981734369155505
  (1279996, 318303)	0.21254698865277744
  (1279996, 373144)	0.35212500999832036
  (1279996, 390130)	0.2206474219107611
  (1279996, 412553)	0.18967045002348673
  (1279996, 434014)	0.27189450523324465
  (1279997, 5685)	0.48650358607431304
  (1279997, 112591)	0.7574829183045267
  (1279997, 273084)	0.4353549002982409
  (1279998, 93795)	0.21717768937055476
  (1279998, 124765)	0.32241752985927996
  (1279998, 153281)	0.28378968751027456
  (1279998, 156297)	0.3137096161546449
  (1279998, 162047)	0.34691726958159064
  (1279998, 169461)	0.2659980990397061
  (1279998, 275288)	0.38703346602729577
  (1279998, 385313)	0.4103285865588191
  (1279998, 412553)	0.2816582375021589
  (1279998, 435463)	0.2851807874350361
  (1279999, 31410)	0.248792678366695
  (1279999, 96224)	0.5416162421321443
  (1279999, 135384)	0.6130934129868719
  (1279999, 242268)	0.19572649660865402
  (1279999, 433612)	0.3607341026233411
  (1279999, 435572)	0.31691096877786484

In [45]:
print(x_test)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2289192 stored elements and shape (320000, 461488)>
  Coords	Values
  (0, 15110)	0.1719352837797837
  (0, 31168)	0.1624772418052177
  (0, 67828)	0.26800375270827315
  (0, 106069)	0.36555450010904555
  (0, 132364)	0.255254889555786
  (0, 138164)	0.23688292264071406
  (0, 171378)	0.2805816206356074
  (0, 271016)	0.45356623916588285
  (0, 279082)	0.17825180109103442
  (0, 388348)	0.2198507607206174
  (0, 398906)	0.34910438732642673
  (0, 409143)	0.3143047059807971
  (0, 420984)	0.17915624523539805
  (1, 6463)	0.30733520460524466
  (1, 15110)	0.211037449588008
  (1, 145393)	0.575262969264869
  (1, 217562)	0.40288153995289894
  (1, 256777)	0.28751585696559306
  (1, 348135)	0.4739279595416274
  (1, 366203)	0.24595562404108307
  (2, 22532)	0.3532582957477176
  (2, 34401)	0.37916255084357414
  (2, 89448)	0.36340369428387626
  (2, 183312)	0.5892069252021465
  (2, 256834)	0.2564939661498776
  :	:
  (319994, 443794)	0.2782185641032538
  (319995, 107868)	0.33399349737546963
  (319995, 109379)	0.3020896484890833
  (319995, 155493)	0.2770682832971669
  (319995, 213324)	0.2683969144317079
  (319995, 232891)	0.2574127854589077
  (319995, 296662)	0.3992485679384015
  (319995, 315813)	0.2848229914563413
  (319995, 324496)	0.36131679336475747
  (319995, 416257)	0.23816465111736282
  (319995, 420984)	0.22631428606830148
  (319995, 444934)	0.32110928175992615
  (319996, 397506)	0.9101400928717545
  (319996, 438709)	0.4143006291901984
  (319997, 98792)	0.4463892055808332
  (319997, 169411)	0.403381646999604
  (319997, 261286)	0.37323893626855326
  (319997, 288421)	0.48498483387153407
  (319997, 349904)	0.32484594100566083
  (319997, 416695)	0.29458327588067873
  (319997, 444770)	0.2668297951055569
  (319998, 130192)	0.6941927210956169
  (319998, 438748)	0.719789181620468
  (319999, 389755)	0.9577980203954275
  (319999, 400636)	0.2874420848216212

In [46]:
# train ml model
model = LogisticRegression(max_iter=1000)

In [47]:
model.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [48]:
# evaluation

# Accuracy train
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)

In [49]:
print('Accuracy score of the training data : ', training_data_accuracy)

Accuracy score of the training data :  0.79871953125

In [50]:
# Accuracy test
x_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction, y_test)

In [51]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.77668125

In [52]:
# saving train model
import pickle

In [53]:
filename = 'trained_model.sav'
pickle.dump(model, open(filename, 'wb'))

In [54]:
# loading saved model
loaded_model = pickle.load(open('/content/trained_model.sav', 'rb'))

In [56]:
x_new = x_test[200]
print(y_test[200])

1

In [57]:
prediction = loaded_model.predict(x_new)
print(prediction)

[1]

In [58]:
if (prediction[0] == 0):
  print('Negative Tweet')
else:
  print('Positive Tweet')

Positive Tweet

In [59]:
x_new = x_test[3]
print(y_test[3])

prediction = loaded_model.predict(x_new)
print(prediction)

if (prediction[0] == 0):
  print('Negative Tweet')
else:
  print('Positive Tweet')

0
[0]
Negative Tweet